### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create HTML skeleton with links to JS and CSS files
- [x] Create a green background
- [x] Create an absolutely positioned image element with the car as the source
- [x] style image element if necessary
- [x] remove any unnecessary css
- [x] fix any bugs
