### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] create data model to store the current direction the car is facing
- [x] make a DOM query to select the image element
- [x] create CSS classes for the car facing: North, South, East, West
- [x] include transitions in the CSS to make the turning smooth
- [x] add an event listener to the window object to listen for "keypress"
- [x] in the callback function for the event listener, switch the class to the appropriate direction depending on which arrow key was pressed
- [x] remove unnecessary css
- [x] fix any bugs
