### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add values of x and y coordinates in the cars data model
- [x] use the existing event listener to listen for a spacebar press
- [x] add a condition in the callback function to move the car a few pixels every 16 milliseconds
- [x] clean up any unused CSS
- [x] fix any bugs
