### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by Jktanisaka** [Jktanisaka/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] use the same event listener to listen for a spacebar press
- [ ] add property in data model to whether the car is on or not
- [ ] modify the callback function to check if the car is already running
    - [ ]  if the car is running, stop the car (stop interval)
    - [ ]  if the car is not running, start the car (start interval)
- [ ] clean up any unused css
- [ ] fix any bugs
